############## WJetsToLNu ##############
WtoLNu_amcatnloFXFX:
  sampleType: W
############## QCD_PT-*_EMEnriched ##############

QCD_PT_10to30_EMEnriched:
  sampleType: QCDEM
QCD_PT_30to50_EMEnriched:
  sampleType: QCDEM
QCD_PT_50to80_EMEnriched:
  sampleType: QCDEM
QCD_PT_80to120_EMEnriched:
  sampleType: QCDEM
QCD_PT_120to170_EMEnriched:
  sampleType: QCDEM
QCD_PT_170to300_EMEnriched:
  sampleType: QCDEM
QCD_PT_300toInf_EMEnriched:
  sampleType: QCDEM

############## QCD_PT-*to*_MuEnriched ##############

QCD_PT_15to20_MuEnrichedPt5:
  sampleType: QCDMu
QCD_PT_20to30_MuEnrichedPt5:
  sampleType: QCDMu
QCD_PT_30to50_MuEnrichedPt5:
  sampleType: QCDMu
QCD_PT_50to80_MuEnrichedPt5:
  sampleType: QCDMu
QCD_PT_80to120_MuEnrichedPt5:
  sampleType: QCDMu
QCD_PT_120to170_MuEnrichedPt5:
  sampleType: QCDMu
QCD_PT_170to300_MuEnrichedPt5:
  sampleType: QCDMu
QCD_PT_300to470_MuEnrichedPt5:
  sampleType: QCDMu
QCD_PT_470to600_MuEnrichedPt5:
  sampleType: QCDMu
QCD_PT_600to800_MuEnrichedPt5:
  sampleType: QCDMu
QCD_PT_800to1000_MuEnrichedPt5:
  sampleType: QCDMu
QCD_PT_1000_MuEnrichedPt5:
  sampleType: QCDMu
############## QCD_HT*to* ##############
QCD_HT70to100_MLM:
  sampleType: QCD_HT
QCD_HT100to200_MLM:
  sampleType: QCD_HT
QCD_HT200to400_MLM:
  sampleType: QCD_HT
QCD_HT400to600_MLM:
  sampleType: QCD_HT
QCD_HT600to800_MLM:
  sampleType: QCD_HT
QCD_HT800to1000_MLM:
  sampleType: QCD_HT
QCD_HT1000to1200_MLM:
  sampleType: QCD_HT
QCD_HT1200to1500_MLM:
  sampleType: QCD_HT
QCD_HT1500to2000_MLM:
  sampleType: QCD_HT
QCD_HT2000toInf_MLM:
  sampleType: QCD_HT
############## QCD_PT-*to* ##############
QCD_PT_15to30:
  sampleType: QCD_PT
QCD_PT_30to50:
  sampleType: QCD_PT
QCD_PT_50to80:
  sampleType: QCD_PT
QCD_PT_80to120:
  sampleType: QCD_PT
QCD_PT_120to170:
  sampleType: QCD_PT
QCD_PT_170to300:
  sampleType: QCD_PT
QCD_PT_300to470:
  sampleType: QCD_PT
QCD_PT_470to600:
  sampleType: QCD_PT
QCD_PT_600to800:
  sampleType: QCD_PT
QCD_PT_800to1000:
  sampleType: QCD_PT
QCD_PT_1000to1400:
  sampleType: QCD_PT
QCD_PT_1400to1800:
  sampleType: QCD_PT
QCD_PT_1800to2400:
  sampleType: QCD_PT
QCD_PT_2400to3200:
  sampleType: QCD_PT
QCD_PT_3200:
  sampleType: QCD_PT
############## TT ##############
# TT:
#   sampleType: TT
TTto2L2Nu:
  sampleType: TT
TTto4Q:
  sampleType: TT
TTtoLNu2Q:
  sampleType: TT
#Sometimes the 'To' is 'to'
#This took like 3 hours of my life away ):
# TTto2L2Nu:
#   sampleType: TT
# TTto4Q:
#   sampleType: TT
# TTtoLNu2Q:
#   sampleType: TT


############## DY ##############
DYto2L_M_10to50_amcatnloFXFX:
  sampleType: DY
DYto2L_M_50_amcatnloFXFX:
  sampleType: DY

############## EWK ##############


############## single Higgs ##############


############## VH non-inclusive ##############


############## VV inclusive ##############
WW:
  sampleType: VV
WZ:
  sampleType: VV
ZZ:
  sampleType: VV


############## VVV inclusive ##############


############## ST #############
ST_s_channel_antitop_4f_leptonDecays:
  sampleType: ST
ST_s_channel_top_4f_leptonDecays:
  sampleType: ST
ST_t_channel_antitop_4f_InclusiveDecays:
  sampleType: ST
ST_t_channel_top_4f_InclusiveDecay:
  sampleType: ST
ST_tW_antitop_2L2Nu:
  sampleType: ST
ST_tW_antitop_4Q:
  sampleType: ST
ST_tW_antitop_LNu2Q:
  sampleType: ST
ST_tW_top_2L2Nu:
  sampleType: ST
ST_tW_top_4Q:
  sampleType: ST
ST_tW_top_LNu2Q:
  sampleType: ST

############## TTX inclusive ##############
TTWW:
  sampleType: TTVV
TTWH:
  sampleType: TTVV
TTZH:
  sampleType: TTVV
TTZZ:
  sampleType: TTVV
TTZToQQ:
  sampleType: TTV

############## ttH ##############